spring:

  jackson:
    serialization.WRITE_DATES_AS_TIMESTAMPS: false
    default-property-inclusion: "NON_EMPTY"

  redis:
    database: 1
    host: localhost
    port: 6379
    password: password123
  cache:
    type: redis

  datasource:
    url: jdbc:postgresql://localhost:5434/test
    username: usage
    password: usage
    dbcp2:
      pool-prepared-statements: true
      max-open-prepared-statements: 32
    hikari:
      maximum-pool-size: 50
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: validate
    show-sql: true
    open-in-view: false