apiVersion: v1
kind: ConfigMap
metadata:
  name: challenge
data:
  application.yml: |-
    spring:
      jackson:
        serialization.WRITE_DATES_AS_TIMESTAMPS: false
        default-property-inclusion: "NON_EMPTY"
      redis:
        database: 1
        host: redis-service
        port: 6379
        password: testPASS!!!
      cache:
        type: redis
      datasource:
        url: jdbc:postgresql://postgresql-service:5432/test
        username: test
        password: testPASS!!!
        dbcp2:
          pool-prepared-statements: true
          max-open-prepared-statements: 32
        hikari:
          maximum-pool-size: 50
      jpa:
        hibernate:
          naming:
            implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
          ddl-auto: validate
        show-sql: true
        open-in-view: false
